name = "serie-a-tv-audience"
main = "worker/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "serie-a-tv-audience"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
